blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from .views import *


app_name = BlogConfig.name


urlpatterns = [
    path('', never_cache(PostListView.as_view()), name='post_list'),
    path('blog/<slug:slug>', PostDetailView.as_view(), name='post_detail'),
    path('create', PostCreateView.as_view(), name='post_create'),
    path('update/<slug:slug>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='post_delete'),
    path('toggle/<slug:slug>', login_required(toggle_publish), name='toggle_publish'),
    path('allposts', PostAllListView.as_view(), name='all_posts'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import *
from django.conf import settings
# from config import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# handler404 = pageNotFound

blog/models.py
from django.db import models
from django.urls import reverse

from users.models import User

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    """
    Класс для работы с моделью Постов.
    """
    name = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.CharField(max_length=255, unique=True,  verbose_name='URL')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='post/', verbose_name='Изображение', **NULLABLE)
    creation_date = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    is_published = models.BooleanField(verbose_name='Признак публикации', default=True)
    view_count = models.PositiveIntegerField(verbose_name='Количество просмотров', default=0)
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    created_by = models.ForeignKey('users.User', verbose_name='Автор', on_delete=models.CASCADE, related_name='post', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('name', 'slug', '-creation_date',)
        permissions = [
            (
                'can_change_post',
                'Can change post'
            ),
        ]

    def increase_views(self):
        """
        Метод увеличивает количество просмотров.
        """
        self.view_count += 1
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

from blog.models import Post
from blog.services import send_post_email


# Create your views here.

class PostListView(ListView):
    """
    Класс для отображения только разрешенных к публикации постов.
    """
    model = Post
    extra_context = {
        'title': 'SkyVillage',  # дополнение к статической информации
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        if self.request.user.has_perm('blog.can_change_post'):
            return queryset
        return queryset


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.increase_views()
        if obj.view_count == 100:
            send_post_email(obj)
        return obj


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('name', 'content', 'image', 'is_published', 'user',)
    success_url = reverse_lazy('blog:post_list')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()

        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('name', 'content', 'image', 'is_published', 'user',)

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', args=[str(self.object.slug)])


def toggle_publish(request, slug):
    """
    Функция переключения публикации поста.
    """
    post_detail = get_object_or_404(Post, slug=slug)
    if post_detail.is_published:
        post_detail.is_published = False
    else:
        post_detail.is_published = True

    post_detail.save()

    return redirect(reverse('blog:post_list'))


class PostAllListView(LoginRequiredMixin, ListView):
    """
    Класс для отображения всех постов (как опубликованных, так и неопубликованных).
    """
    model = Post
    extra_context = {
        'title': 'Все записи SkyVillage',  # дополнение к статической информации
    }

blog/templates/blog/post_confirm_delete.html
{% extends 'main/base.html' %}<!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% load mediapath %}
{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены, что хотите удалить запись "{{ object }}"?<br> <br> <!-- <br> отступ -->
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">   <!-- ШАБЛОННЫЙ ТЕГ Условия -->
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

blog/templates/blog/post_detail.html
{% extends 'main/base.html' %}
{% load cache %}
{% load mediapath %}

{% block content %}

{% cache 60 post %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Заголовок</td>
                        <td>{{ object.name }} ({{ object.slug }})</td>
                    </tr>
                    <tr>
                        <td>Содержимое</td>
                        <td>{{ object.content|linebreaks }}</td>
                    </tr>
                    <tr>
                        <td>Изображение</td>
                        <td><p><img src="{% mediapath object.image %}" width="150" height="120" alt="Картинка"></p></td>
                    </tr>
                    <tr>
                        <td>Дата публикации</td>
                        <td>{{ object.creation_date }}</td>
                    </tr>
                    <tr>
                        <td>Количество просмотров</td>
                        <td>{{ object.view_count }}</td>
                    </tr>

                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary"><< Назад</a>
                </a>
            </div>
        </div>
    </div>
    <div class="card-footer text-light">
        <p class="card-text">
            Создана: {{ object.user }}<br>
        </p>
    </div>
         {% endcache %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input type="submit" class="btn btn-success border-warning"  value="{% if object %}Сохранить{% else %}Создать{% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'blog:post_list' %}" class="btn btn-primary border-info"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-12 text-light">Добро пожаловать в SkyVillage!</h1>
        <h4 class="display-12 text-warning">Начните свое общение, создав свой пост!</h4>
    <img src="{% static 'img/blog/blogg.jpeg' %}" alt="Картинка" width="690" height="380">
</div>
{% if user.is_authenticated  or user.is_superuser %}
<div class="col-12">
        <p><a href="{% url 'blog:post_create' %}" class="btn btn-primary border-info mx-3 ">Создать публикацию</a></p>
       {% endif %}
     {% if perms.blog.can_change_post or user.is_superuser %}
       <p> <a href="{% url 'blog:all_posts' %}" class="btn btn-primary border-info mx-3 ">Показать все записи</a></p>
       {% endif %}
</div>

<div class="container">
    {% if object_list %}
        <div class="row text-center">
            {% for object in object_list %}
            {% include 'blog/includes/inc_post_card.html' %}
            {% endfor %}
    </div>
    {% else %}
        <h3>Публикаций нет</h3>
    <h3>:-(</h3>
    {% endif %}
</div>
 <style>
        .btn {
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
  </style>
{% endblock %}