blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from .views import *


app_name = BlogConfig.name


urlpatterns = [
    path('', never_cache(PostListView.as_view()), name='post_list'),
    path('blog/<slug:slug>', PostDetailView.as_view(), name='post_detail'),
    path('create', PostCreateView.as_view(), name='post_create'),
    path('update/<slug:slug>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='post_delete'),
    path('toggle/<slug:slug>', login_required(toggle_publish), name='toggle_publish'),
    path('allposts', PostAllListView.as_view(), name='all_posts'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import *
from django.conf import settings
# from config import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# handler404 = pageNotFound

main/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from django.views.decorators.cache import never_cache, cache_page

from main.apps import MainConfig
from .views import *


app_name = MainConfig.name


urlpatterns = [
    path('', never_cache(IndexView.as_view()),  name='index'),  # http://127.0.0.1:8000/
    path('client/',  cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client/<int:pk>/', never_cache(ClientDetailView.as_view()), name='client_detail'),
    path('client/create/', never_cache(ClientCreateView.as_view()), name='client_create'),
    path('client/update/<int:pk>/', never_cache(ClientUpdateView.as_view()), name='client_update'),
    path('client/delete/<int:pk>/', never_cache(ClientDeleteView.as_view()), name='client_delete'),
    path('message/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', never_cache(MessageDetailView.as_view()), name='message_view'),
    path('message/create/', never_cache(MessageCreateView.as_view()), name='message_create'),
    path('message/update/<int:pk>/', never_cache(MessageUpdateView.as_view()), name='message_update'),
    path('message/delete/<int:pk>/', never_cache(MessageDeleteView.as_view()), name='message_delete'),
    path('sending/', cache_page(60)(SendingListView.as_view()), name='sending_list'),
    path('sending/<int:pk>/', cache_page(60)(SendingDetailView.as_view()), name='sending_view'),
    path('sending/create/', never_cache(SendingCreateView.as_view()), name='sending_create'),
    path('sending/update/<int:pk>/', never_cache(SendingUpdateView.as_view()), name='sending_update'),
    path('sending/delete/<int:pk>/', never_cache(SendingDeleteView.as_view()), name='sending_delete'),
    path('attempt/', cache_page(60)(AttemptListView.as_view()), name='attempt_list'),
    path('attempt/<int:pk>/', cache_page(60)(AttemptDetailView.as_view()), name='attempt_view'),
    path('set_status_sending/<int:pk>', login_required(set_status_sending), name='set_status_sending'),
    path('set_is_active/<int:pk>', login_required(set_is_active), name='set_is_active'),
]

main/models.py
from datetime import date, datetime
from django.db import models
from config.settings import AUTH_USER_MODEL

# Create your models here.


NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """
    Класс для работы с моделью Клиента сервиса.
    """
    name = models.CharField(max_length=150, verbose_name='Имя', **NULLABLE)
    email = models.EmailField(max_length=150, verbose_name='Почта', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    # author = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    created_by = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Кем создан',
                                   related_name='client', **NULLABLE)

    # поле определения активных клиентов
    is_active = models.BooleanField(default=True, verbose_name='Активный')

    def __str__(self):
        """
        Магический метод для отображения информации об объекте класса для пользователей.
        """
        return f'{self.email} ({self.name})'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('email',)  # сортировка, '-email' - сортировка в обратном порядке
        permissions = [
            (
                'can_view_client',
                'Can view client'
            ),
            (
                'can_block_client',
                'Can block client'
            ),
        ]


class Message(models.Model):
    """
    Класс для работы с моделью Сообщения для рассылки.
    """
    subject = models.CharField(max_length=255, verbose_name='Тема сообщения')
    body = models.TextField(verbose_name='Текст сообщения')
    created_at = models.DateTimeField(auto_now_add=True)
    # author = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        """
        Магический метод для отображения информации об объекте класса для пользователей.
        """
        return self.subject


class Sending(models.Model):
    """
    Класс для работы с моделью настройки Рассылки.
    """
    ONCE = 'Один раз'
    DAILY = '1 раз в день'
    WEEKLY = '1 раз в неделю'
    MONTHLY = '1 раз в месяц'

    FREQUENCY_CHOICES = [
        (ONCE, 'Один раз'),
        (DAILY, '1 раз в день'),
        (WEEKLY, '1 раз в неделю'),
        (MONTHLY, '1 раз в месяц'),
    ]

    CREATED = 'Создана'
    COMPLETED = 'Завершена'
    LAUNCHED = 'Запущена'

    SELECT_STATUS = [
        (CREATED, 'Создана'),
        (COMPLETED, 'Завершена'),
        (LAUNCHED, 'Запущена'),
    ]

    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    scheduled_time = models.TimeField(auto_now_add=True, verbose_name='Время рассылки')
    # created_at = models.DateTimeField(auto_now_add=True)
    start_date = models.DateField(default=date.today, verbose_name='Дата начала')
    end_date = models.DateField(default=date.today, verbose_name='Дата окончания')
    frequency = models.CharField(max_length=30, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=50, default='Создана', choices=SELECT_STATUS, verbose_name='Статус')
    # author = models.CharField(max_length=50, verbose_name='Отправитель', **NULLABLE)
    created = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Кем создано',
                                related_name='clients', **NULLABLE)

    def __str__(self):
        """
        Магический метод для отображения информации об объекте класса для пользователей.
        """
        return f'ID: {self.id} - время рассылки: {self.scheduled_time}'

    class Meta:
        """
        Класс мета-настроек.
        """
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            (
                'set_sending_status',
                'Can set sending status'
            ),
            (
                'can_view_sending',
                'Can view sending'
            ),
        ]


class Attempt(models.Model):
    """
    Класс для работы с моделью настройки Попытки Рассылки.
    """
    DELIVERED = 'delivered'
    NOT_DELIVERED = 'not_delivered'

    STATUS = (
        (DELIVERED, 'доставлено'),
        (NOT_DELIVERED, 'не доставлено'),
    )

    sending = models.ForeignKey(Sending, on_delete=models.CASCADE, verbose_name='Рассылка')
    sent_at = models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки')
    status = models.CharField(choices=STATUS, verbose_name='Статус')
    response = models.TextField(**NULLABLE, verbose_name='Ответ сервера')

    def __str__(self):
        """
        Магический метод для отображения информации об объекте класса для пользователей.
        """
        return f"{self.sending.message.subject} - {self.sent_at}"

    class Meta:
        verbose_name = 'Статистика (попытка)'
        verbose_name_plural = 'Статистики (попытки)'

main/views.py
from random import sample
import django

from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from blog.models import Post
from main.models import *
from main.services import send_email_to_clients
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class IndexView(TemplateView):
    template_name = 'main/index.html'
    extra_context = {
        'title': 'SkyForest',
        'object_list': Sending.objects.all()
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_posts = list(Post.objects.filter(is_published=True))
        context['random_blog_posts'] = sample(all_posts, min(3, len(all_posts)))
        return context


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'object_list': Client.objects.all(),
        'title': 'Все клиенты'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('main.can_view_client'):
            return queryset
        return Client.objects.filter(created_by=self.request.user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    extra_context = {
        'title': 'Детали клиента'
    }


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('name', 'email', 'comment', 'created_by',)
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        """Метод добавления создателя клиента"""
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('name', 'email', 'comment', 'created_by', 'is_active',)

    def get_success_url(self):
        return reverse('main:client_detail', args=[str(self.object.pk)])


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'message_list': Message.objects.all(),
        'title': 'Все Сообщения'
    }


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    success_url = reverse_lazy('main:message_list')


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('subject', 'body', 'user',)
    success_url = reverse_lazy('main:message_list')

    def form_valid(self, form):
        """Метод добавления создателя сообщения"""
        form.instance.user = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ('subject', 'body', 'user',)

    def get_success_url(self):
        return reverse('main:message_view', args=[str(self.object.pk)])


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:message_list')


class SendingListView(LoginRequiredMixin, ListView):
    model = Sending
    extra_context = {
        'object_list': Sending.objects.all(),
        'title': 'Все Рассылки'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('main.can_view_sending'):
            return queryset
        return Sending.objects.filter(created=self.request.user)


class SendingDetailView(LoginRequiredMixin, DetailView):
    model = Sending


class SendingCreateView(LoginRequiredMixin, CreateView):
    model = Sending
    fields = ('message', 'frequency', 'status', 'created', 'start_date', 'end_date',)
    success_url = reverse_lazy('main:sending_list')

    def form_valid(self, form):
        """Метод добавления создателя сообщения"""
        form.instance.created = self.request.user
        return super().form_valid(form)

    try:
        for send in Sending.objects.all():
            if send.status == Sending.CREATED:
                send_email_to_clients(Sending.ONCE)
    except django.db.utils.ProgrammingError:
        print('ProgrammingError')


class SendingUpdateView(LoginRequiredMixin, UpdateView):
    model = Sending
    fields = ('message', 'frequency', 'status',)

    def get_success_url(self):
        return reverse('main:sending_view', args=[str(self.object.pk)])


class SendingDeleteView(LoginRequiredMixin, DeleteView):
    model = Sending
    success_url = reverse_lazy('main:sending_list')


class AttemptListView(LoginRequiredMixin, ListView):
    model = Attempt
    extra_context = {
        'object_list': Attempt.objects.all(),
        'title': 'Статистика рассылок'
    }


class AttemptDetailView(LoginRequiredMixin, DetailView):
    model = Attempt
    extra_context = {
        'title': 'Детали рассылки'
    }


def set_is_active(request, pk):
    client_item = get_object_or_404(Client, pk=pk)
    if client_item.is_active:
        client_item.is_active = False
    else:
        client_item.is_active = True
    client_item.save()
    return redirect(reverse('main:client_list'))


def set_status_sending(request, pk):
    sending_item = get_object_or_404(Sending, pk=pk)
    if sending_item.status == Sending.CREATED:
        sending_item.status = Sending.COMPLETED
        sending_item.save()
    else:
        sending_item.status = Sending.CREATED
        sending_item.save()
    return redirect(reverse('main:sending_list'))


# def pageNotFound(request, exception):
#     return HttpResponseNotFound('<h1>Страница не найдена</h1>')

main/templates/main/attempt_detail.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}
    <div class="card">
        <div class="card-header">{{ object.sending }}</div>
        <div class="card-body">
            <table class="table table-striped">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ object.sent_at }}</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title pricing-card-title">{{ object.status }}</h6>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="card-title pricing-card-title">{{ object.response }}</li>
                        </ul>
                    </div>
                </div>
            </table>
        </div>
        <div class="card-footer">
            <a href="{% url 'main:client_list' %}" type="button"
               class="w-100 btn btn-lg btn-outline-primary">назад</a>
        </div>
    </div>
{% endblock %}

main/templates/main/attempt_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    <main>
         <div class="pricing-header px-1 py-1 pt-md-1 pb-md-1 mx-auto text-center">
            <img class="rounded-circle" src="{% static 'img/main/forest.jpg' %}" alt="Картинка" width="500" height="300">
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for object in object_list %}

                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h5 class="my-0 fw-normal">{{ object.sending }}</h5>
                        </div>
                        <div class="card-body bg-info">
                            <ul class="list-unstyled mt-3 mb-4">
                                <li class="card-title pricing-card-title">{{ object.sent_at }}</li>
                            </ul>
                            <ul class="list-unstyled mt-3 mb-4">
                                <li class="card-title pricing-card-title">{{ object.status }}</li>
                            </ul>
                            <p><a class="btn btn-secondary" href="{% url 'main:attempt_view' object.pk %}">Посмотреть
                                &raquo;</a></p>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
 <style>
        .btn {
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
  </style>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/base.html
{% load static %} <!-- Статика -->
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/styles.css">
<style>
	body {
   	   background: 	#008B8B;
	   color: #00ffff;
   }
   </style>
</head>
<body style="color:#FF8C00" >

<!--     <div class="header-dark">-->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid ">
            <a class="navbar-brand" title="Вернуться на главную страницу" style="color:#00ffff" href="/">SkyForest</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse"   aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                {% include 'main/includes/inc_main_menu.html' %}
                <!-- ШАБЛОННЫЙ ТЕГ include вставляет отдельный html из файла inc_main_menu.html' -->
               <form class="d-flex ">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
         </div>
         <div>

<main class="container marketing ">
    <div class="row gy-10">
        <div class="row">
            <div class="row gy-5">
                {% block content %}  <!-- выводит content из index.html -->
                {% endblock %}
            </div>
        </div>
    </div>
</main>
<div class="container bg-dark">
<footer class="pt-4 my-md-5 pt-md-5 border-top border-info">
    <div class="row ">
        <div class="col-12 col-md">

        </div>
        <div class="col-6 col-md">
            <h5></h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1">

                </li>

            </ul>
        </div>
        <div class="col-6 col-md " >
                <h5>Features</h5>
            <ul class="list-unstyled text-small ">
                <li class="mb-1" >
                   <p><a class="link-secondary text-decoration-none" href="{% url 'main:client_list' %}">Клиенты</a></p>
                    <p><a class="link-secondary text-decoration-none" title="Смелее)" href="mailto:my_danny@mail.ru">
                         Связаться с нами</a></p>
                </li>
            </ul>

                   <div class="row text-center  ">
                        <div class="col-12 "><i>
            (c) Precious Bunny, </i>
                2023
                            </i>
          </div>
                </div>
        </div>

  </div>

<!--&lt;!&ndash;    <address> <i>Russia</i></address>&ndash;&gt;-->
<!--    <div class="row text-center ">-->
<!--            <div class="col-6"><i>-->
<!--            (c) Precious Bunny, </i>-->
<!--                2023</i>-->
<!--            </div>-->
<!--        </div>-->
</footer>
  </div>
               </div>
</body>
</html>

main/templates/main/client_detail.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}
    <div class="card">
        <div class="card-body">
            <table class="table table-striped">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ object.name }}</h5>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title pricing-card-title">{{ object.email }}</h6>
                        <p></p>
                        Комментарий:
                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="card-title pricing-card-title">{{ object.comment }}</li>
                        </ul>
                        <p></p>

                        <ul class="list-unstyled mt-3 mb-4">
                            <li class="card-title pricing-card-title">Кем создан: {{ object.created_by }}</li>
                        </ul>
                        {% if user.is_superuser or perms.main.can_block_client %}
                        <a href="{% url 'main:set_is_active' object.pk %}" class="btn btn-outline-warning float-end">
                            {% if object.is_active %}
                                Деактивировать
                            {% else %}
                                Активировать
                            {% endif %}
                        </a>
                        {% endif %}
                    </div>
                </div>
            </table>
        </div>
        <div class="card-footer">
            <a href="{% url 'main:client_list' %}" type="button"
               class="w-100 btn btn-lg btn-outline-primary">назад</a>
        </div>
    </div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load static %}

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <main>
        <div class="pricing-header px-1 py-1 pt-md-1 pb-md-1 mx-auto text-center">
            <img class="rounded-circle" src="{% static 'img/main/forest.jpg' %}" alt="Картинка" width="500" height="300">
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-12">
                <a href="{% url 'main:client_create' %}" class="btn btn-primary border-info m-2">Создать клиента</a>
            </div>
            {% for object in object_list %}
                {% if user.is_authenticated and object.created_by == user or user.is_superuser or perms.main.can_view_client %}
                    <div class="col-3 text-center">
                        <div class="card mb-4 rounded-3 shadow-sm bg-success">
                            <div class="card-header text-light py-3">
                                <h5 class="my-0 fw-normal">{{ object.name }}</h5>
                            </div>
                            <div class="card-body bg-info">
                                <h6 class="card-title pricing-card-title">{{ object.email }}</h6>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.message }}</li>
                                </ul>
                                <p><a class="btn btn-secondary" href="{% url 'main:client_detail' object.pk %}">Посмотреть
                                    &raquo;</a></p>
                                {%endif%}
                                {% if user.is_authenticated and object.created_by == user or user.is_superuser %}
                                    <p><a class="btn btn-warning" href="{% url 'main:client_update' object.pk %}">Изменить
                                        &raquo;</a></p>
                                    <p><a class="btn btn-danger" href="{% url 'main:client_delete' object.pk %}">Удалить
                                        &raquo;</a></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

            {% endfor %}
        </div>
    </main>
 <style>
        .btn {
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
  </style>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/message_list.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load static %}

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <main>
        <div class="pricing-header px-1 py-1 pt-md-1 pb-md-1 mx-auto text-center">
            <img class="rounded-circle" src="{% static 'img/main/forest.jpg' %}" alt="Картинка" width="500" height="300">
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-12">
                <a href="{% url 'main:message_create' %}" class="btn btn-primary border-info m-2">Создать сообщение</a>
            </div>
            {% for object in object_list %}

                <div class="col">
                    <div class="card  mb-4 rounded-3 shadow-sm bg-primary">
                        <div class="card-header text-light py-3">
                            <h5 class="my-0 fw-normal">{{ object.subject }}</h5>
                        </div>
                        <div class="card-body bg-info">
                            <h6 class="card-title pricing-card-title">{{ object.body }}</h6>
                            <ul class="list-unstyled mt-3 mb-4">
                                <li class="card-title pricing-card-title">{{ object.created_at }}</li>
                            </ul>
                            <p><a class="btn btn-secondary" href="{% url 'main:message_view' object.pk %}">Посмотреть
                                &raquo;</a></p>

                            {% if object.user == user or user.is_superuser %}
                            <p><a class="btn btn-warning" href="{% url 'main:message_update' object.pk %}">Изменить
                                &raquo;</a></p>
                            <p><a class="btn btn-danger" href="{% url 'main:message_delete' object.pk %}">Удалить
                                &raquo;</a></p>
                            {% endif%}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
 <style>
        .btn {
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
  </style>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/sending_list.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load static %}

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <main>
               <div class="pricing-header px-1 py-1 pt-md-1 pb-md-1 mx-auto text-center">
            <img class="rounded-circle" src="{% static 'img/main/forest.jpg' %}" alt="Картинка" width="500" height="300">
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col-12">   <!-- кнопка Создать рассылку -->
                <a href="{% url 'main:sending_create' %}" class="btn btn-primary border-info m-2">Создать рассылку</a>
            </div>
            {% for object in object_list %}
                {% if perms.main.can_view_sending or user.is_superuser %}
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm ">
                            <div class="card-header  py-3">
                                <h5 class="my-0 fw-normal">{{ object.message }}</h5>
                            </div>
                            <div class="card-body bg-info">
                                <h6 class="card-title pricing-card-title">{{ object.created_at }}</h6>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.scheduled_time }}</li>
                                </ul>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.frequency }}</li>
                                </ul>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li class="card-title pricing-card-title">{{ object.status }}</li>
                                </ul>
                                <p><a class="btn btn-secondary" href="{% url 'main:sending_view' object.pk %}">Посмотреть&raquo;</a></p>
                                {% endif %}
                                {% if object.created == user or user.is_superuser %}
                        <div class="col-4">
                              <p><a class="btn btn-secondary" href="{% url 'main:sending_view' object.pk %}">Посмотреть&raquo;</a>
                                    <a class="btn btn-warning" href="{% url 'main:sending_update' object.pk %}">Изменить&raquo;</a>
                                   <a class="btn btn-danger" href="{% url 'main:sending_delete' object.pk %}">Удалить&raquo;</a></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

            {% endfor %}
                        </div>
        </div>
    </main>
 <style>
        .btn {
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
  </style>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->